### PR TITLE
Update containers

### PR DESCRIPTION
**Pull request by draganm**
This change updates container on changes, it can also detect changes when a container config is somehow different to terraforn.

### CODE REVIEW

**Comment by zimbatm** [comment]
I am not sure of the difference between this and using the [docker_container](https://www.terraform.io/docs/providers/docker/r/container.html) resource when the provider is configured with `host = "ssh://..."`.

**Comment by draganm** [comment]
docker_container works only with the local docker, `host` doc says:
host - (Optional, block) See Extra Hosts below for details.

host is a block within the configuration that can be repeated to specify the extra host mappings for the container. Each host block supports the following:

host - (Required, string) Hostname to add.
ip - (Required, string) IP address this hostname should resolve to.
This is equivalent to using the --add-host option when using the run command of the Docker CLI.

so has nothing to do with remote dockers, more adding entries in `/etc/hosts` of the created container.

**Comment by draganm** [comment]
did the manual testing as part of the development process - works fine for all supported attributes

**Comment by zimbatm** [comment]
from: https://www.terraform.io/docs/providers/docker/index.html
> Note You can also use the ssh protocol to connect to the docker host on a remote machine. The configuration would look as follows:
```tf
provider "docker" {
  host = "ssh://user@remote-host:22"
}
```

That being said, having the VM IP passed into a provide config instead of the resource is usually a recipe for annoyance.

**Pull request merged**
